In [1]:
import numpy as np
from scipy.stats import norm

In [2]:
mu = 0.4
sigma = 0.5
dt = 1 / 252
S0 = 1
n = 200

In [3]:
T = np.linspace(0, (n-1)* dt, n)

In [4]:
T

array([0.        , 0.00396825, 0.00793651, 0.01190476, 0.01587302,
       0.01984127, 0.02380952, 0.02777778, 0.03174603, 0.03571429,
       0.03968254, 0.04365079, 0.04761905, 0.0515873 , 0.05555556,
       0.05952381, 0.06349206, 0.06746032, 0.07142857, 0.07539683,
       0.07936508, 0.08333333, 0.08730159, 0.09126984, 0.0952381 ,
       0.09920635, 0.1031746 , 0.10714286, 0.11111111, 0.11507937,
       0.11904762, 0.12301587, 0.12698413, 0.13095238, 0.13492063,
       0.13888889, 0.14285714, 0.1468254 , 0.15079365, 0.1547619 ,
       0.15873016, 0.16269841, 0.16666667, 0.17063492, 0.17460317,
       0.17857143, 0.18253968, 0.18650794, 0.19047619, 0.19444444,
       0.1984127 , 0.20238095, 0.20634921, 0.21031746, 0.21428571,
       0.21825397, 0.22222222, 0.22619048, 0.23015873, 0.23412698,
       0.23809524, 0.24206349, 0.24603175, 0.25      , 0.25396825,
       0.25793651, 0.26190476, 0.26587302, 0.26984127, 0.27380952,
       0.27777778, 0.28174603, 0.28571429, 0.28968254, 0.29365

In [5]:
T.shape

(200,)

In [6]:
W = np.zeros(n)

In [9]:
W

array([ 0.00000000e+00, -1.87922797e-02,  1.74890222e-02,  5.19336536e-02,
        4.54894964e-02,  5.49532616e-02,  9.54037469e-02,  1.60249073e-01,
        2.02659731e-01,  1.27176254e-01,  8.80679586e-02,  1.32407330e-01,
        2.27686405e-01,  2.66626517e-01,  2.11836533e-01,  2.77066222e-01,
        2.93385464e-01,  2.77534793e-01,  2.34904943e-01,  1.87818615e-01,
        2.52986477e-01,  1.02858128e-01,  1.61406883e-01,  2.11879304e-01,
        2.12638440e-01,  2.46245343e-01,  2.98471564e-01,  2.90508056e-01,
        3.17593458e-01,  3.17817896e-01,  3.19654740e-01,  2.95423779e-01,
        3.41953445e-01,  3.14682856e-01,  3.22035743e-01,  3.98156607e-01,
        3.42092984e-01,  3.57244094e-01,  3.89174587e-01,  3.53005662e-01,
        4.28201878e-01,  4.43973759e-01,  4.49603226e-01,  4.27442451e-01,
        3.75330196e-01,  4.52957032e-01,  4.33135703e-01,  5.39288302e-01,
        4.60986024e-01,  4.70213027e-01,  4.58136713e-01,  3.64008580e-01,
        3.52587690e-01,  

In [8]:
W[1:] = np.cumsum(norm.rvs(size=n-1) * np.sqrt(dt))

In [11]:
X = np.exp((mu - sigma**2/2)*  T + sigma * W)

In [12]:
X

array([1.        , 0.99172952, 1.01098697, 1.02967234, 1.02748064,
       1.03348127, 1.05574797, 1.09172982, 1.11634508, 1.0761712 ,
       1.05648428, 1.08134716, 1.13534712, 1.15893301, 1.12884619,
       1.16754372, 1.17839465, 1.17036888, 1.14693748, 1.12147349,
       1.15988242, 1.07717916, 1.11039008, 1.14001208, 1.14169009,
       1.1623042 , 1.19435799, 1.19091071, 1.2084666 , 1.20992185,
       1.21235587, 1.199064  , 1.22862709, 1.21331142, 1.21910995,
       1.26778686, 1.23408796, 1.24483007, 1.26624464, 1.2449089 ,
       1.29401752, 1.30568648, 1.31079647, 1.29776795, 1.26577043,
       1.31730194, 1.30573521, 1.37841437, 1.32693791, 1.33452942,
       1.32794396, 1.2682767 , 1.26243182, 1.29135176, 1.36367352,
       1.39080377, 1.4592892 , 1.48614531, 1.39068485, 1.41260782,
       1.44029698, 1.42670749, 1.35313411, 1.3694511 , 1.37860814,
       1.40034238, 1.32608462, 1.31909444, 1.30608294, 1.28272534,
       1.35842764, 1.41863183, 1.36497474, 1.36741262, 1.42561